replicaCount: 1

image:
  repository: gcr.io/devopsduniya/auth-service
  pullPolicy: IfNotPresent
  tag: "latest"

mongoUri: "mongodb://mongo:27017/devopsduniya"

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:
  path: /readiness
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5

service:
  port: 80