replicaCount: 1

image:
  repository: gcr.io/devopsduniya/auth-service
  pullPolicy: IfNotPresent
  tag: "latest"

mongoUri: "mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongo:27017/devopsduniya"

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  path: /readiness
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10

service:
  port: 80