apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: devopsduniya-dev
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: MONGO_URI
          value: {{ .Values.mongoUri }}
        - name: CLIENT_ID
          value: {{ .Values.env.clientId }}
        - name: CLIENT_SECRET
          value: {{ .Values.env.clientSecret }}
        - name: REFRESH_TOKEN
          value: {{ .Values.env.refreshToken }}
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.livenessProbe.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.readinessProbe.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
